### ISSUE TITLE
Concurrent operations?

### ISSUE THREAD

**Issue by chbndrhnns** [garden-rs/garden#43]
Hi,

Is it possible to execute a command concurrently on a query? I am thinking something like `poetry lock` in a Python setting. It takes some time and would like to execute it concurrently, maybe limited by the number of CPU cores or some other limit.

**Comment by davvid** [comment]
Good idea. There's not currently a way to do this.

You could make it work by adding `&` to the command recipes so that commands get kicked off in the background, but that's not really a great solution.

I've wanted this as well -- basically, adding a `-j/--jobs` option to enable parallel execution of jobs.

There are some questions (e.g. should we blindly run everything in parallel or should we group by command or tree?) so we'll have to sort that out. The simplest naive implementation would be to just run everything in parallel and not try too hard to deal with the interspersed stdout or command order (e.g. whether command "A" should run before command "B").

That's probably a fine place to start since it'll unlock most of the functionality.

**Comment by davvid** [comment]
#45 is adding a `-j | --jobs=N` option. If it's the very last option you can just say `-j` and it's equivalent to `--jobs=0` (or `-j 0`) which makes it use all available cores (just like `make`). The zero (0) value for the `--jobs` option is special-cased to behave that way.

Thanks for the sug ~ this was a good and fun feature to implement.

**Comment by davvid** [comment]
Oh, and I should mention that I was able to retain the "A runs before B" and "C runs after B" feature for pre and post-commands.

We parallelize across Trees for "custom commands" (`garden my-command [<query>]`) and for the "garden cmd" sub-command (`garden cmd <query> <cmd> [<cmd>..]`).

Custom commands are invoked with an implicit single named command and a tree query that can resolve to multiple trees. For this reason, "custom commands" parallelize across trees and run the custom command over all of the resolved trees in parallel.

We parallelize across Commands instead of Trees when the `-b | --breadth-first` option is specified to `garden cmd ...`. This is useful with "garden cmd" because it allows one or more commands to be named.

Without `-b`, running  `garden cmd -j4 my-trees a b c` runs all of the commands in parallel per-tree, one tree at a time. This means that "a", "b" and "c" are all running concurrently on the tree. This is the "depth first" mode.

With `-b` (`--breadth-first`), running `garden cmd -j4 -b my-trees a b c` visits all of the trees in parallel and runs the commands in order, one after the other, "a", "b" and "c" in each tree. This happens concurrently across all trees.

Pre and post-commands always run in order -- those are the only ones that are not subject to running in parallel by design.

`garden` doesn't currently have a mode where it will parallelize across both Commands and Trees so that every single named command is running concurrently across all resolved trees. Iff that ends up being a useful addition I could look into adding that as well, though we'd probably have to introduce another option to enable it. `-J#` or `-p#` might be good candidate options in case you have an opinion.

The feature implemented in #45 does seem like it should handle most use cases, so we can let it cook in the wild a bit before to see if any real-world scenarios come up where it would be useful to add the fully-parallel mode.
